apiVersion: v1
kind: ConfigMap
metadata:
  name: rrfashion-config
  namespace: rrfashion
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/rr_fashion?schema=public"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "minio"
  MINIO_PORT: "9000"
  MINIO_BUCKET: "rrfashion"
  MINIO_USE_SSL: "false"
  JWT_EXPIRES_IN: "15m"
  JWT_ADMIN_EXPIRES_IN: "15m"
  REFRESH_EXPIRES_IN: "7d"
  BCRYPT_SALT_ROUNDS: "12"
  CORS_ORIGINS: "https://15cf-2409-40c1-5024-1636-5dad-b2fa-6542-45da.ngrok-free.app,https://9852-152-59-41-217.ngrok-free.app,https://ashup1711.github.io"
  COOKIE_SAMESITE: "none"
  RATE_LIMIT_GENERAL: "500"
  RATE_LIMIT_AUTH: "30"
